"""change col1 to col2

Revision ID: 2bddb1382e90
Revises: 7d8393d2872f
Create Date: 2019-10-09 09:44:58.758000

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = '2bddb1382e90'
down_revision = '7d8393d2872f'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('food', sa.Column('addcol2', sa.String(length=64), nullable=True))
    op.drop_column('food', 'addcol1')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('food', sa.Column('addcol1', mysql.VARCHAR(length=64), nullable=True))
    op.drop_column('food', 'addcol2')
    # ### end Alembic commands ###
