"""ceshi

Revision ID: bf401f4ab33e
Revises: 38c88b3c2f6d
Create Date: 2019-10-09 09:53:56.523000

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'bf401f4ab33e'
down_revision = '38c88b3c2f6d'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('food', sa.Column('addcol2', sa.String(length=64), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('food', 'addcol2')
    # ### end Alembic commands ###
